### ISSUE TITLE
Maximum Request Number

### ISSUE THREAD

**Issue by MatheGoD** [filiptronicek/gh-sponsors-api#18]
First of all, thank you very much for your generosity of making this kind of api..

But I found a little awkward...

Count API doesn't give me count of sponsors if a github user has sponsors...

On top of that I just want to know the maximum number of request...because while testing  your API I found out that If I requested your API several times with the same user, it give me  server error..

Please let me know.

**Comment by filiptronicek** [comment]
Hey there @MatheGoD 👋, I just pushed https://github.com/filiptronicek/gh-sponsors-api/commit/bff5c26e6371ee461f577837443123a18c1210b7 and that adds the `/api/v2/count` endpoint, so you can try it as follows:
```
GET https://gh-sponsors-filiptronicek.vercel.app/v2/count/{username}
```

This should fix the count issues.
