### ISSUE TITLE
Endpoint to get active sponsors

### ISSUE THREAD

**Issue by achimmihca** [filiptronicek/gh-sponsors-api#24]
Is there a way to query for active sponsors?
I did not find a way to determine this from the JSON response.

**Comment by filiptronicek** [comment]
This is a current limitation of the `sponsors_partial` method we're doing now. I think it would be nice to have in v2 of the `/sponsors/` endpoint.

**Comment by filiptronicek** [comment]
Fixed by https://github.com/filiptronicek/gh-sponsors-api/commit/639023a734d1dae7af9eea561de9cb44c4c9ae32

**Comment by filiptronicek** [comment]
(please use `/v2/sponsors/{user}` now)

**Comment by achimmihca** [comment]
The v2 endpoint returns "404 not found". Example: https://ghs.vercel.app/v2/sponsors/filiptronicek

**Comment by filiptronicek** [comment]
Sorry for that @achimmihca, it seems like there has been an error in the build. Should be sorted out now

**Comment by achimmihca** [comment]
Thanks for implementing this.

However, "current" and "past" sponsors are swapped.
Otherwise it seems to work.

Should I open a new issue?

**Comment by filiptronicek** [comment]
@achimmihca please do open one, I'll have a look soon.
