### ISSUE TITLE
"current" and "past" sponsors are swapped in sponsors endpoint

### ISSUE THREAD

**Issue by achimmihca** [filiptronicek/gh-sponsors-api#27]
It seems the current sponsors are listed under "past" and the past sponsors are listed under "current" in the JSON.

Example: [filiptronicek](https://github.com/filiptronicek) has currently 3 public visible sponsors. But these are shown under "past" in the JSON that is returned from https://ghs.vercel.app/v2/sponsors/filiptronicek

**Comment by filiptronicek** [comment]
Sorry for the slow turnaround here, @achimmihca, and thanks for reporting. Would you be able to contribute a fix? Very happy to review and land this.
