### ISSUE TITLE
`500: INTERNAL_SERVER_ERROR` for `https://ghs.vercel.app/v2/count/marcuswhybrow`

### ISSUE THREAD

**Issue by marcuswhybrow** [filiptronicek/gh-sponsors-api#31]
Hi,

`https://ghs.vercel.app/v2/count/filiptronicek` works as expected and produces:

```json
{
  "status": "success",
  "sponsors": {
    "current": 3,
    "past": 12
  }
}
```

But `https://ghs.vercel.app/v2/count/marcuswhybrow` give the error:

```
00: INTERNAL_SERVER_ERROR 
Code: FUNCTION_INVOCATION_FAILED 
ID: lhr1::thxwg-1713617338689-f4e0d1a2cfbd
```

Here's the screengrab too:

![image](https://github.com/filiptronicek/gh-sponsors-api/assets/278456/46045b2d-66ce-46db-9e0c-b48aa568cae4)

Cheers,
Marcus

**Comment by filiptronicek** [comment]
Hey @marcuswhybrow, I have just pushed a commit which should fix this incorrect behavior. Let me know if you encounter further issues.
