### ISSUE TITLE
Limit / Page Size too small

### ISSUE THREAD

**Issue by mrousavy** [filiptronicek/gh-sponsors-api#36]
Hey filip - thanks so much for this, this API is really helpful.

Unfortunately I noticed that the API has a small page size and does not include all sponsors.

In my case, I have 165 past sponsors and 62 active sponsors:

![image](https://github.com/filiptronicek/gh-sponsors-api/assets/15199031/295ace7f-5aa6-40be-b162-64caca23d8fa)

..but your API (https://ghs.vercel.app/v2/sponsors/mrousavy) unfortunately only includes 40 past sponsors and 14 current sponsors (so 54 in total, whereas it should've been 227 in total).

I've seen your discussion post in the GitHub community forum (https://github.com/orgs/community/discussions/3818) - but I don't think there's an official REST API endpoint for sponsors yet, right?

**Comment by filiptronicek** [comment]
Hi @mrousavy 👋, and thanks for the report. The v2 of the API simply worked by scraping the https://github.com/sponsors/user/ endpoint directly, and therefore could not by itself interactively load further sponsors. I have tried using GitHub's own pagination endpoint and have implemented a draft of that in #37.

Can you try if the v3 endpoint returns what you expect? I hope it should take into account all of your sponsors now. Note that it will not consider private sponsorships, but I hope we'll be able to have a `/v3/sponsors/count` endpoint which would take them into account as well.

https://ghs.vercel.app/v3/sponsors/mrousavy

**Comment by mrousavy** [comment]
Amazing stuff filip - this works like a charm for me! :) Thank you!

**Comment by filiptronicek** [comment]
Glad it does! Also, thanks for seeding some more test data to my API responses :)
<img width="824" alt="image" src="https://github.com/filiptronicek/gh-sponsors-api/assets/29888641/f19005a9-d491-4157-b288-97f73cc68f8a">
